import type { Metadata } from 'next';
import NextTopLoader from 'nextjs-toploader';
import { AppProviders } from '@/providers';
import { Toaster } from 'react-hot-toast';
import { INTER_CLASS } from '@/styles';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${INTER_CLASS} antialiased`}>
        <NextTopLoader />
        <AppProviders>{children}</AppProviders>
        <Toaster
          toastOptions={{
            duration: 6000
          }}
        />
      </body>
    </html>
  );
}
