import type { Metadata } from "next";
import "./globals.css";
import { inter } from "@/lib/fonts";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import Header2 from "@/components/layout/Header2";
import ReduxStoreProvider from "@/lib/redux/ReduxStoreProvider";
import AuthPersistorClient from "@/components/custom-utils/persistors/AuthPersistorClient";
import { getOrDetectLocation } from "@/lib/location-utils";
import CustomGlobalAlert from "@/components/custom-utils/alerts/CustomGlobalAlert";
import { TicketUserProvider } from "@/contexts/TicketUserProvider";
import { getCurrentUser } from "@/actions/get-auth-userdata";
import { getTicketSession } from "@/actions/get-ticket-session";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [locationData, user, ticketSession] = await Promise.all([
    getOrDetectLocation(),
    getCurrentUser(),
    getTicketSession()
  ])
  
  return (
    <html lang="en">
      <ReduxStoreProvider>
        <TicketUserProvider user={user} ticketSession={ticketSession}>
          <body
            className={`${inter.className}`}
          >
            <AuthPersistorClient currency={locationData.currency} region={locationData.region} />
            <CustomGlobalAlert />
            <Header2 />
            <Header />
            {children}
            <Footer />
          </body>
        </TicketUserProvider>
      </ReduxStoreProvider>
    </html>
  )
}
