import type { Metadata } from "next";
import "./globals.css";
import { inter } from "@/lib/redux/fonts";
import Header from "@/components/layout/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gray-50 `}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
